server:
  port: 8899
  context-path: /emp
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    type: com.alibaba.druid.pool.DruidDataSource
    username: hr
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:/com/baizhi/mapper/*Impl.xml